"""PostgreSQL migration with JSONB fields

Revision ID: effcfd30b18a
Revises: 
Create Date: 2025-08-14 13:30:18.383323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'effcfd30b18a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lv1_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lv1_texts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lv1_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lv2_texts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lv2_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lv2_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lv3_situations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lv3_ads', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lv3_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sb1_text', sa.Text(), nullable=True),
    sa.Column('sb1_options', sa.Text(), nullable=True),
    sa.Column('sb1_answers', sa.Text(), nullable=True),
    sa.Column('sb2_text', sa.Text(), nullable=True),
    sa.Column('sb2_words', sa.Text(), nullable=True),
    sa.Column('sb2_answers', sa.Text(), nullable=True),
    sa.Column('hv1_audio_url', sa.String(length=500), nullable=True),
    sa.Column('hv1_statements', sa.Text(), nullable=True),
    sa.Column('hv1_answers', sa.Text(), nullable=True),
    sa.Column('hv2_audio_url', sa.String(length=500), nullable=True),
    sa.Column('hv2_statements', sa.Text(), nullable=True),
    sa.Column('hv2_answers', sa.Text(), nullable=True),
    sa.Column('hv3_audio_url', sa.String(length=500), nullable=True),
    sa.Column('hv3_statements', sa.Text(), nullable=True),
    sa.Column('hv3_answers', sa.Text(), nullable=True),
    sa.Column('sa_task_a', sa.Text(), nullable=True),
    sa.Column('sa_task_b', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('exam_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'target_lang', name='uq_exam_translation_latest')
    )
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'path', 'source_lang', 'target_lang', 'source_hash', name='uq_translation_cache_unique_entry')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exam_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_result')
    op.drop_table('user')
    op.drop_table('translation_cache')
    op.drop_table('exam_translation')
    op.drop_table('exam')
    # ### end Alembic commands ###
